name: Build Application

on:
  push:
    branches:
      - 'main'

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: dev-youngestdev
    
    - name: "Deploy application"
      uses: okteto/apply@latest
      with:
        namespace: dev-youngestdev
        manifest: docker-compose.yml

    - name: "Push changes"
      uses: okteto/push@latest
      with:
        namespace: dev-youngestdev
        name: google-bgn
